name: functions
description: Cloud Functions for Sentry Mobile

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.9.0
  build_node_compilers: ^0.2.4

dependencies:
  # firebase_admin: 0.1.2+1
  # firebase_admin_interop: 2.1.0
  firebase_functions_interop: ^1.0.2
