name: build
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  build:
    name: ${{ matrix.target }} | ${{ matrix.os }} | ${{ matrix.channel }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # max-parallel: 4
      matrix:
        os: [macos-latest]
        target: ['ios', 'android', 'web']
        channel: ['stable', 'beta']
        exclude:
          # No web on stable yet
          - channel: stable
            target: web
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
              java-version: '8'
        - uses: subosito/flutter-action@v1
          with:
            channel: ${{ matrix.channel }}
        - name: enable web
          if: matrix.target == 'web'
          run: flutter config --enable-web
        - name: Test
          run: flutter test
        - name: Build ${{ matrix.target }}
          run: |
            TARGET=${{ matrix.target }}
            case $TARGET in
            ios)
            flutter build ios --release --no-codesign
            ;;
            android)
            flutter build appbundle
            ;;
            web)
            flutter build web
            ;;
            esac